# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include: 
    - master 
  paths:
    exclude: 
    - ReadMe.MD 
pool:
  vmImage: 'windows-latest'
steps:
- script: C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe /target:library /out:$(System.DefaultWorkingDirectory)\mtr.dll $(System.DefaultWorkingDirectory)\messagetablereader.cs
  displayName: "Build Library using csc.exe"
- powershell: |
    Add-Type -Path $(System.DefaultWorkingDirectory)\mtr.dll
    $mtr = New-Object MessageTableReader.Reader
    if ($mtr.GetMessage(16392) -eq 'MD45') {
      return $true
    }
    else {
      return $false
    }